services:
  app:
    build:
      context: .
    ports:
      - "7453:7453"
    environment:
      - DATABASE_HOST=database
      - DATABASE_USER=${DATABASE_USER:-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-password}
      - DATABASE_NAME=${DATABASE_NAME:-mydatabase}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - DATABASE_SSLMODE=disable
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=7453
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app_network

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_NAME:-mydatabase}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app_network:

volumes:
  db_data:
    driver: local
