services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: my-jenkins-server
    ports:
      - "8080:8080"
      - "50000:50000" # Maps port 50000 on the host to port 50000 in the container (for Jenkins agents)
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Allows Jenkins to manage Docker containers
    environment:
      - JENKINS_OPTS="--httpPort=8080"
      # - JAVA_OPTS="-Djenkins.install.runSetupWizard=false" # Optional: Uncomment to skip the initial setup wizard (requires pre-configuration or security setup)
    restart: unless-stopped

volumes:
  jenkins_home:
    driver: local
